# Generated by Django 4.2.2 on 2023-06-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('b_staff_image', models.ImageField(upload_to='myMedia')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('customer_image', models.ImageField(upload_to='myMedia')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Food_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('Buff', 'Buff'), ('Chicken', 'Chicken'), ('Veg', 'Vegetarian')], max_length=20)),
                ('price', models.IntegerField()),
                ('food_image', models.ImageField(upload_to='myMedia')),
            ],
        ),
        migrations.CreateModel(
            name='Team_staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('team_staff_image', models.ImageField(upload_to='myMedia')),
            ],
        ),
    ]
