# Generated by Django 4.2.2 on 2023-06-20 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0006_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
